### PR TITLE
Close file after unzip operation

### PR DESCRIPTION
**Pull request by davidanthoff**

### CODE REVIEW

**Comment by davidanthoff** [comment]
@samoconnor Bump, any chance you could merge this and tag a new version?

**Comment by davidanthoff** [comment]
@samoconnor Are you still maintaining this repo? If not, should we move it into some other account so that other folks can have commit access and merge stuff?

**Comment by samoconnor** [comment]
Hi @davidanthoff,

Thanks for the PR.

Sorry about the delay, my availability for Julia package maintenance is intermittent.
I'd be happy for this package to be taken over by https://github.com/JuliaIO or a similar group.
I'm not sure how to go about that. @ararslan? @nalimilan?

Cheers,

Sam

**Comment by davidanthoff** [comment]
Thanks! I think moving this over to JuliaIO would be great. Also pinging @tkelman, he seems to be the master of everything.

**Comment by davidanthoff** [comment]
Oh, and could you tag a new version in METADATA?

**Comment by samoconnor** [comment]
done: https://github.com/JuliaLang/METADATA.jl/pull/8526

**Comment by nalimilan** [comment]
Moving the package to JuliaIO would imply that some maintainers of this package are members of that organization, which doesn't seem to be the case. Though you could make a call for volunteers.

**Comment by samoconnor** [comment]
Hi @nalimilan, @ararslan,

@davidanthoff suggested moving "into some other account so that other folks can have commit access". This seems like a good idea to me as there will be intermittent periods when I'm unable to spend time on Julia stuff.

How can I help?
If you add me to the JuliaIO Organisation, can I then move InfoZIP.jl to there?

**Comment by ararslan** [comment]
Alternatively, you can grant people commit access to this repository, so they can merge pull requests, make releases, etc. when you're not available. That's likely the better option, since, as Milan said, none of the maintainers of this package are JuliaIO members.

**Pull request merged**
